apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-seed-v2
  namespace: travel-web-dev
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: seed
        image: 443014729163.dkr.ecr.ap-southeast-1.amazonaws.com/travel-web-app:latest
        command: ["node", "/scripts/seed.js"]
        workingDir: /app
        env:
        - name: NODE_PATH
          value: /app/node_modules
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: travel-web-secrets
              key: DATABASE_URL
        volumeMounts:
        - name: seed-script
          mountPath: /scripts
      volumes:
      - name: seed-script
        configMap:
          name: seed-script
      restartPolicy: Never
