apiVersion: batch/v1
kind: Job
metadata:
  name: microservice-seed
  namespace: travel-web-dev
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: seed
        image: node:20-alpine
        command: ["node", "/scripts/seed.js"]
        env:
        - name: AUTH_DB_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: travel-web-secrets
              key: AUTH_DATABASE_URL
        - name: BOOKING_DB_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: travel-web-secrets
              key: BOOKING_DATABASE_URL
        - name: ROOM_DB_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: travel-web-secrets
              key: ROOM_DATABASE_URL
        - name: PAYMENT_DB_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: travel-web-secrets
              key: PAYMENT_DATABASE_URL
        - name: REVIEW_DB_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: travel-web-secrets
              key: REVIEW_DATABASE_URL
        - name: NOTIFICATION_DB_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: travel-web-secrets
              key: NOTIFICATION_DATABASE_URL
        - name: CONTENT_DB_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: travel-web-secrets
              key: CONTENT_DATABASE_URL
        - name: BLOG_DB_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: travel-web-secrets
              key: BLOG_DATABASE_URL
        volumeMounts:
        - name: seed-script
          mountPath: /scripts
      volumes:
      - name: seed-script
        configMap:
          name: seed-script
      restartPolicy: Never
