apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: travel-web-staging
resources:
  - ../../base

namePrefix: staging-

patches:
  - path: patches/resources.yaml
  - path: patches/env.yaml

replicas:
  - name: travel-web
    count: 2

images:
  - name: travel-web-app
    newName: 443014729163.dkr.ecr.ap-southeast-1.amazonaws.com/travel-web-app
    newTag: latest

labels:
  - pairs:
      environment: staging

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=staging
      - DEBUG=false
