apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: travel-web

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  # - db-migration-job.yaml  # Disabled: run migrations manually
  - external-secret.yaml
  - storage-class.yaml

images:
  - name: travel-web-app
    newName: 443014729163.dkr.ecr.ap-southeast-1.amazonaws.com/travel-web-app
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: travel-web
