# Main service for travel-web application
apiVersion: v1
kind: Service
metadata:
  name: travel-web
  labels:
    app: travel-web
spec:
  selector:
    app: travel-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
